# Generated by Django 3.1.7 on 2021-04-13 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneotp',
            name='count',
        ),
        migrations.RemoveField(
            model_name='phoneotp',
            name='email',
        ),
        migrations.RemoveField(
            model_name='phoneotp',
            name='otp_session_id',
        ),
        migrations.RemoveField(
            model_name='phoneotp',
            name='password',
        ),
        migrations.RemoveField(
            model_name='phoneotp',
            name='username',
        ),
        migrations.RemoveField(
            model_name='phoneotp',
            name='validated',
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='otp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='phone',
            field=models.CharField(default='+254', max_length=12),
        ),
    ]
